# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e897c9ec32bd76132651058daaac9f10ad06308ae8fe9f7abf24bfab3ba8cf66bb33273696c8240f8fb878225ba80a8b75c0cfd37f062581cbeccafff2359af6

test:
  secret_key_base: 70706ec7e93bc79d2e3783eac06e1b2c8d001c646775771c58df65dce284de6a93e170f968636730def56c44f04b45648cbebafdf95915a0583ab05133e2c34d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
